# -*- coding: utf-8 -*-
"""TubeclassificationusinghybridmodelReviewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14tkKYOwNhQ-voPEtPEbtC2N-KCk3UjTP

# **Complete Hybrid Fusion model for water classification**
"""

# %% [markdown]
# # Tube Sample Classification Pipeline
# **Methodology:** Image Preprocessing → ResNet50V2 Deep Features + Handcrafted Features (Color / Texture / Quality) → Feature Fusion → Regularized Autoencoder with Latent-Dimension Search → Latent Feature Representation → ML Classifiers (Decision Tree, Random Forest, Gradient Boosting, AdaBoost, SVM, XGBoost), each **hyperparameter-tuned with RandomizedSearchCV**, trained with **5-Fold CV on the Training set only**, then evaluated on held-out **Validation** and **Test** sets.
# ```
# Train/Class0/*.jpg  Train/Class1/*.jpg
# Validation/Class0/*.jpg  Validation/Class1/*.jpg
# Test1/Class0/*.jpg  Test1/Class1/*.jpg
# ```

# %% [markdown]
# ## 0. Setup

# %%
# If running in Google Colab, mount Drive first.
# stdout is redirected while mounting so Colab's own status message
# (e.g. "Drive already mounted at /content/drive; ...") is not printed
# to the output screen.
import io, contextlib
try:
    from google.colab import drive
    with contextlib.redirect_stdout(io.StringIO()):
        drive.mount('/content/drive')
except Exception:
    pass

# %%
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "opencv-python-headless", "scikit-image", "xgboost", "scikit-learn",
                "seaborn", "matplotlib", "pandas", "tqdm", "openpyxl", "scipy", "psutil"])

# %%
import os, time, warnings, pickle, tracemalloc
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import cv2
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.ticker as mticker
import seaborn as sns

from skimage.feature import graycomatrix, graycoprops, local_binary_pattern
from skimage.measure import shannon_entropy

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                              roc_auc_score, log_loss, confusion_matrix, roc_curve, auc,
                              mean_squared_error)
from scipy.stats import shapiro, randint, uniform, loguniform

import tensorflow as tf
from tensorflow.keras import layers, callbacks
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.resnet_v2 import ResNet50V2, preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# %% [markdown]
# ## 0.1 Global Plot Styling
# Centralised styling so every figure in the notebook shares a bold, high-contrast
# palette and consistent typography instead of the default dull matplotlib/seaborn look.

# %%
PALETTE_ABLATION = {
    "Handcrafted Only":            "#B0B7BE",   # soft grey — weakest baseline
    "ResNet50v2 Only":             "#7FA6D9",   # dusty blue
    "Fused (HC + RN)":             "#F2B279",   # soft amber
    "Fused + Autoencoder (Latent)": "#6FC2A4",  # sage green — proposed / best
}

PALETTE_CLASSIFIER = {
    "Decision Tree":      "#E28B6D",
    "Random Forest":      "#6FBF8B",
    "Gradient Boosting":  "#6C93C7",
    "AdaBoost":           "#B48EC9",
    "SVM":                "#E297B4",
    "XGBoost":             "#E8C36E",
}

ACCENT_GOOD = "#5FB38A"   # proposed pipeline / correct predictions
ACCENT_BAD  = "#D98679"   # overfit gap / incorrect predictions
ACCENT_GRID = "#E9ECEF"

sns.set_theme(style="whitegrid")
mpl.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "axes.edgecolor": "#495057",
    "axes.labelcolor": "#212529",
    "axes.titlecolor": "#212529",
    "axes.titleweight": "bold",
    "axes.titlesize": 13,
    "axes.labelsize": 11,
    "axes.labelweight": "medium",
    "axes.grid": True,
    "grid.color": ACCENT_GRID,
    "grid.linewidth": 0.6,
    "text.color": "#212529",
    "xtick.color": "#343A40",
    "ytick.color": "#343A40",
    "legend.frameon": False,
    "legend.fontsize": 9.5,
    "font.family": "DejaVu Sans",
    "font.size": 10.5,
    "savefig.dpi": 180,
    "savefig.facecolor": "white",
    "figure.dpi": 110,
})

def style_ablation_legend(ax, title="Feature Set"):
    leg = ax.legend(title=title, bbox_to_anchor=(1.02, 1), loc="upper left")
    if leg:
        leg.get_title().set_fontweight("bold")
    return ax

def annotate_bars(ax, fmt="{:.2f}", fontsize=7.5, color="#343A40", rotation=90):
    """Vertical, non-overlapping bar-value labels (avoids the crowded
    horizontal-label overlap seen with many bars per group)."""
    for container in ax.containers:
        try:
            labels = ax.bar_label(container, fmt=fmt, fontsize=fontsize, color=color,
                                   padding=3, rotation=rotation)
            if rotation:
                for lab in labels:
                    lab.set_va("bottom" if rotation == 90 else "center")
                    lab.set_ha("center")
        except Exception:
            pass
    top = ax.get_ylim()[1]
    ax.set_ylim(top=top * 1.18)

def ordered_ablation_colors(labels):
    return [PALETTE_ABLATION.get(l, "#ADB5BD") for l in labels]

def ordered_classifier_colors(labels):
    return [PALETTE_CLASSIFIER.get(l, "#ADB5BD") for l in labels]

# ---- KDE-safety wrappers -------------------------------------------------
from numpy.linalg import LinAlgError as _NPLinAlgError
try:
    from scipy.linalg import LinAlgError as _SPLinAlgError
except Exception:
    _SPLinAlgError = _NPLinAlgError
_KDE_ERRORS = (_NPLinAlgError, _SPLinAlgError, ValueError)

def safe_histplot(ax=None, **kwargs):
    try:
        return sns.histplot(ax=ax, **kwargs)
    except _KDE_ERRORS:
        if ax is not None:
            ax.clear()
        kwargs["kde"] = False
        return sns.histplot(ax=ax, **kwargs)

def safe_violinplot(ax=None, **kwargs):
    try:
        return sns.violinplot(ax=ax, **kwargs)
    except _KDE_ERRORS:
        if ax is not None:
            ax.clear()
        fallback_kwargs = {k: v for k, v in kwargs.items() if k not in ("split", "cut", "inner")}
        return sns.boxplot(ax=ax, **fallback_kwargs)

# %% [markdown]
# ## 1. Configuration — dataset paths

# %%
train_dir = "/content/drive/MyDrive/Train"
val_dir   = "/content/drive/MyDrive/Validation"
test_dir  = "/content/drive/MyDrive/Test"

IMG_SIZE = (224, 224)      # ResNet50V2 input size
OUT_DIR  = "/content/drive/MyDrive/tube_pipeline_outputs"
os.makedirs(OUT_DIR, exist_ok=True)

# (Train class list no longer printed to keep the output screen clean —
# available via sorted(os.listdir(train_dir)) if needed.)

# %% [markdown]
# ## 2. Load file paths + labels

# %%
def list_images_labels(root_dir):
    paths, labels = [], []
    classes = sorted(os.listdir(root_dir))
    for c in classes:
        cdir = os.path.join(root_dir, c)
        if not os.path.isdir(cdir):
            continue
        for f in os.listdir(cdir):
            if f.lower().endswith((".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")):
                paths.append(os.path.join(cdir, f))
                labels.append(c)
    return paths, labels

train_paths, train_labels_raw = list_images_labels(train_dir)
val_paths,   val_labels_raw   = list_images_labels(val_dir)
test_paths,  test_labels_raw  = list_images_labels(test_dir)

le = LabelEncoder().fit(train_labels_raw)
y_train = le.transform(train_labels_raw)
y_val   = le.transform(val_labels_raw)
y_test  = le.transform(test_labels_raw)

N_CLASSES = len(le.classes_)
AVERAGE = 'binary' if N_CLASSES == 2 else 'weighted'

PALETTE_CLASSES = {i: c for i, c in enumerate(
    sns.color_palette("Set2", max(N_CLASSES, 3)).as_hex()[:N_CLASSES]
)}

# (Split counts and class list no longer printed to keep the output screen
# clean — available via len(train_paths)/len(val_paths)/len(test_paths) and
# list(le.classes_) if needed. See Section 12 / 21 for the hyperparameter
# and results tables that ARE displayed.)

# %% [markdown]
# ## 3. Image Preprocessing

# %%
def preprocess_image(path, size=IMG_SIZE):
    img = cv2.imread(path)
    if img is None:
        raise ValueError(f"Could not read image: {path}")
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, size, interpolation=cv2.INTER_AREA)
    img = cv2.GaussianBlur(img, (3, 3), 0)   # mild denoise
    return img

# %% [markdown]
# ## 4. Handcrafted Features — Color, Texture, Quality

# %%
def color_features(img):
    feats = []
    for i in range(3):                       # RGB mean/std
        ch = img[:, :, i].astype(np.float32)
        feats += [ch.mean(), ch.std()]
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    for i in range(3):                        # HSV mean/std
        ch = hsv[:, :, i].astype(np.float32)
        feats += [ch.mean(), ch.std()]
    for i in range(3):                        # RGB 8-bin histograms
        hist = cv2.calcHist([img], [i], None, [8], [0, 256]).flatten()
        hist = hist / (hist.sum() + 1e-8)
        feats += hist.tolist()
    return np.array(feats)

def texture_features(gray):
    glcm = graycomatrix(gray, distances=[1, 2], angles=[0, np.pi/4, np.pi/2, 3*np.pi/4],
                         levels=256, symmetric=True, normed=True)
    props = ['contrast', 'dissimilarity', 'homogeneity', 'energy', 'correlation', 'ASM']
    feats = []
    for p in props:
        feats += graycoprops(glcm, p).flatten().tolist()
    lbp = local_binary_pattern(gray, P=8, R=1, method='uniform')
    hist, _ = np.histogram(lbp, bins=np.arange(0, 11), density=True)
    feats += hist.tolist()
    return np.array(feats)

def quality_features(gray):
    lap_var = cv2.Laplacian(gray, cv2.CV_64F).var()          # blur / sharpness proxy
    brightness = gray.mean()
    contrast = gray.std()
    entropy = shannon_entropy(gray)
    sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    sharpness = np.sqrt(sobelx**2 + sobely**2).mean()
    return np.array([lap_var, brightness, contrast, entropy, sharpness])

def extract_handcrafted(img):
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    return np.concatenate([color_features(img), texture_features(gray), quality_features(gray)])

# %% [markdown]
# ## 5. ResNet50V2 Deep Feature Extraction

# %%
_resnet_base = ResNet50V2(include_top=False, weights='imagenet', pooling='avg',
                          input_shape=(*IMG_SIZE, 3))
_resnet_model = Model(inputs=_resnet_base.input, outputs=_resnet_base.output)

def extract_resnet_batch(images):
    arr = np.array(images, dtype=np.float32)
    arr = preprocess_input(arr)
    return _resnet_model.predict(arr, batch_size=32, verbose=0)

# %% [markdown]
# ## 6. Build & Cache Feature Sets (Handcrafted / ResNet / Fused) for Train, Val, Test

# %%
def build_feature_sets(paths, cache_name, batch_size=32):
    """
    Builds (or loads from cache) handcrafted / ResNet50V2 / fused features for a
    given split. The cache is keyed only by `cache_name` (e.g. "train"), so if the
    underlying image folder changes size between runs (files added/removed, a
    fresh dataset dropped in the same Drive path, etc.) a stale .npz from a
    previous run could silently be reused — its row count would then disagree
    with the current `paths` / `y_*` arrays and blow up downstream (e.g. boolean
    indexing against y_train in the AE diagnostics). To prevent that, the cache
    is only trusted if its row count matches len(paths); otherwise it is
    discarded and rebuilt from scratch.
    """
    cache_path = os.path.join(OUT_DIR, f"{cache_name}_features.npz")
    if os.path.exists(cache_path):
        d = np.load(cache_path)
        if len(d['hc']) == len(paths):
            return d['hc'], d['rn'], d['fused']
        # else: stale cache silently discarded and features are re-extracted
        # below (no message printed to keep the output screen clean; the
        # row-count safety check itself is still enforced).

    hc_list, rn_list = [], []
    for i in tqdm(range(0, len(paths), batch_size), desc=f"Extracting {cache_name}"):
        batch_paths = paths[i:i + batch_size]
        batch_imgs = [preprocess_image(p) for p in batch_paths]
        for img in batch_imgs:
            hc_list.append(extract_handcrafted(img))
        rn_list.append(extract_resnet_batch(batch_imgs))

    hc = np.vstack(hc_list)
    rn = np.vstack(rn_list)
    fused = np.hstack([hc, rn])
    np.savez_compressed(cache_path, hc=hc, rn=rn, fused=fused)
    return hc, rn, fused

HC_train, RN_train, FUSED_train = build_feature_sets(train_paths, "train")
HC_val,   RN_val,   FUSED_val   = build_feature_sets(val_paths, "val")
HC_test,  RN_test,  FUSED_test  = build_feature_sets(test_paths, "test")

print("Handcrafted dim:", HC_train.shape[1], "| ResNet50V2 dim:", RN_train.shape[1],
      "| Fused dim:", FUSED_train.shape[1])

# %% [markdown]
# ## 7. Regularized Autoencoder with Latent-Dimension Search → Latent Representation
# Trained **only on the training set** (scaler + autoencoder fit on Train, applied to
# Val/Test) to avoid leakage. Several candidate latent dimensions are tried and the
# one with the lowest **validation** reconstruction loss is kept.

# %%
INPUT_DIM_FUSED = FUSED_train.shape[1]
LATENT_DIMS = [32, 64, 128]
AE_EPOCHS   = 80
AE_BATCH    = 32
AE_PATIENCE = 12

def build_autoencoder(input_dim, latent_dim, l2_reg=1e-4):
    reg = l2(l2_reg)
    inp = layers.Input(shape=(input_dim,))
    # ── Encoder ──
    x = layers.Dense(512, activation='relu', kernel_regularizer=reg)(inp)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)
    x = layers.Dense(256, activation='relu', kernel_regularizer=reg)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    encoded = layers.Dense(latent_dim, activation='relu',
                            kernel_regularizer=reg, name='latent')(x)
    # ── Decoder ──
    x = layers.Dense(256, activation='relu', kernel_regularizer=reg)(encoded)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(512, activation='relu', kernel_regularizer=reg)(x)
    x = layers.BatchNormalization()(x)
    decoded = layers.Dense(input_dim, activation='linear')(x)

    ae  = Model(inp, decoded, name=f'AE_{latent_dim}')
    enc = Model(inp, encoded, name=f'Enc_{latent_dim}')
    ae.compile(optimizer=Adam(5e-4), loss='mse')
    return ae, enc

def fit_best_ae(X_train_sc, X_val_sc):
    best_ld, best_vl = None, np.inf
    best_enc_w, best_ae_w = None, None
    histories = {}

    for ld in LATENT_DIMS:
        tf.keras.backend.clear_session()
        ae, enc = build_autoencoder(X_train_sc.shape[1], ld)
        es = callbacks.EarlyStopping(monitor='val_loss', patience=AE_PATIENCE,
                                      restore_best_weights=True, verbose=0)
        h = ae.fit(X_train_sc, X_train_sc,
                   validation_data=(X_val_sc, X_val_sc),
                   epochs=AE_EPOCHS, batch_size=AE_BATCH,
                   callbacks=[es], verbose=0)
        vl = min(h.history['val_loss'])
        histories[ld] = h.history
        print(f"  [AE] latent_dim={ld:>4d}  best val_loss={vl:.5f}")
        if vl < best_vl:
            best_vl = vl
            best_ld = ld
            best_enc_w = enc.get_weights()
            best_ae_w = ae.get_weights()

    tf.keras.backend.clear_session()
    best_ae, best_enc = build_autoencoder(X_train_sc.shape[1], best_ld)
    best_enc.set_weights(best_enc_w)
    best_ae.set_weights(best_ae_w)
    return best_enc, best_ae, best_ld, histories, best_vl

fused_scaler = StandardScaler().fit(FUSED_train)
FUSED_train_sc = fused_scaler.transform(FUSED_train)
FUSED_val_sc   = fused_scaler.transform(FUSED_val)
FUSED_test_sc  = fused_scaler.transform(FUSED_test)

print("Searching autoencoder latent dimension ...")
encoder, autoencoder, BEST_LATENT_DIM, ae_histories, best_ae_val_loss = fit_best_ae(
    FUSED_train_sc, FUSED_val_sc
)
print(f"Selected latent dimension: {BEST_LATENT_DIM}  (val MSE={best_ae_val_loss:.5f})")

LATENT_train = encoder.predict(FUSED_train_sc, verbose=0)
LATENT_val   = encoder.predict(FUSED_val_sc, verbose=0)
LATENT_test  = encoder.predict(FUSED_test_sc, verbose=0)

recon_train = autoencoder.predict(FUSED_train_sc, verbose=0)
RE_train = np.mean((FUSED_train_sc - recon_train) ** 2, axis=1)

# %% [markdown]
# ## 7.1 Autoencoder Diagnostics (Final Proposed Model)
# NOTE: These 5 plots (7.1a–7.1e) are supplementary methodology diagnostics for the
# autoencoder itself. They are NOT part of the reviewer's cross-validation request
# (that is addressed separately in Sections 9, 11, 12 and 12.1). The code below is
# left intact — and each figure is still computed and saved to `OUT_DIR` as a PNG —
# but `plt.show()` has been replaced with `plt.close(fig)` so these plots are not
# rendered inline when the notebook is run, keeping the output focused on the
# fold-wise CV results the reviewer asked for.

# %%
# ── 7.1a Latent-dimension search bar chart ──────────────────────────────────
dims = list(ae_histories.keys())
vals = [min(ae_histories[d]['val_loss']) for d in dims]
fig, ax = plt.subplots(figsize=(7.5, 4.5))
bar_colors = ordered_classifier_colors(list(PALETTE_CLASSIFIER.keys()))[:len(dims)]
ax.bar([str(d) for d in dims], vals, color=bar_colors, edgecolor="#212529", linewidth=0.8)
best_idx = dims.index(BEST_LATENT_DIM)
ax.bar(str(BEST_LATENT_DIM), vals[best_idx], color=ACCENT_GOOD, edgecolor="#212529",
       linewidth=1.6, label=f"Best = {BEST_LATENT_DIM}")
for d, v in zip(dims, vals):
    ax.text(str(d), v + max(vals) * 0.02, f"{v:.4f}", ha="center", va="bottom", fontsize=9)
ax.set_xlabel("Latent Dimension"); ax.set_ylabel("Best Val MSE Loss")
ax.set_title("Autoencoder: Reconstruction Error vs Latent Dimension")
ax.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "ae_latent_dim_search.png"))
plt.close(fig)

# ── 7.1b Train/val loss curves for every candidate dimension ───────────────
fig, axes = plt.subplots(1, 2, figsize=(13.5, 4.5))
for ld, col in zip(dims, bar_colors):
    h = ae_histories[ld]
    axes[0].plot(h['loss'], label=f"latent={ld}", color=col, linewidth=1.8)
    axes[1].plot(h['val_loss'], label=f"latent={ld}", color=col, linewidth=1.8, linestyle="--")
for ax, t in zip(axes, ["Train Loss (MSE)", "Validation Loss (MSE)"]):
    ax.set_title(t); ax.set_xlabel("Epoch"); ax.set_ylabel("MSE")
    ax.legend(fontsize=8.5)
plt.suptitle("Autoencoder Training Curves — All Candidate Latent Dimensions", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "ae_training_curves_all_dims.png"))
plt.close(fig)

# ── 7.1c Reconstruction-error distribution per class (Train set) ───────────
fig, ax = plt.subplots(figsize=(10, 4.5))
for i, cls in enumerate(le.classes_):
    ax.hist(RE_train[y_train == i], bins=40, alpha=0.6, label=str(cls),
            color=PALETTE_CLASSES[i])
ax.set_xlabel("Reconstruction Error (MSE)"); ax.set_ylabel("Count")
ax.set_title(f"Reconstruction Error per Class (Train Set, latent={BEST_LATENT_DIM})")
ax.legend(title="Class")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "ae_re_distribution_per_class.png"))
plt.close(fig)

# ── 7.1d Per-sample reconstruction error (sorted) ───────────────────────────
fig, ax = plt.subplots(figsize=(10, 4.5))
sidx = np.argsort(RE_train)
ax.bar(range(len(RE_train)), RE_train[sidx],
       color=[PALETTE_CLASSES[y_train[i]] for i in sidx], width=1.0)
ax.set_xlabel("Sample (sorted by reconstruction error)"); ax.set_ylabel("Reconstruction Error")
ax.set_title("Per-Sample Reconstruction Error (Train Set)")
handles = [plt.Rectangle((0, 0), 1, 1, color=PALETTE_CLASSES[i]) for i in range(N_CLASSES)]
ax.legend(handles, le.classes_, title="Class", fontsize=8.5)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "ae_re_per_sample.png"))
plt.close(fig)

# ── 7.1e Latent space: PCA + t-SNE (Train set) ──────────────────────────────
pca2 = PCA(n_components=2, random_state=SEED)
X_pca = pca2.fit_transform(LATENT_train)

fig, axes = plt.subplots(1, 2, figsize=(14, 5.5))
for i, cls in enumerate(le.classes_):
    m = (y_train == i)
    axes[0].scatter(X_pca[m, 0], X_pca[m, 1], s=18, alpha=0.75, label=str(cls),
                     color=PALETTE_CLASSES[i])
axes[0].set_title(f"Latent Space — PCA (latent={BEST_LATENT_DIM})")
axes[0].set_xlabel("PC1"); axes[0].set_ylabel("PC2")
axes[0].legend(title="Class", fontsize=8.5, markerscale=1.5)

try:
    tsne = TSNE(n_components=2, random_state=SEED,
                perplexity=min(30, max(5, len(y_train) // 4)))
    X_ts = tsne.fit_transform(LATENT_train)
    for i, cls in enumerate(le.classes_):
        m = (y_train == i)
        axes[1].scatter(X_ts[m, 0], X_ts[m, 1], s=18, alpha=0.75, label=str(cls),
                         color=PALETTE_CLASSES[i])
    axes[1].set_title(f"Latent Space — t-SNE (latent={BEST_LATENT_DIM})")
    axes[1].set_xlabel("Dim 1"); axes[1].set_ylabel("Dim 2")
    axes[1].legend(title="Class", fontsize=8.5, markerscale=1.5)
except Exception as e:
    axes[1].text(0.5, 0.5, f"t-SNE error:\n{e}", ha="center", va="center",
                 transform=axes[1].transAxes)

plt.suptitle("Autoencoder Latent Space Visualization (Train Set)", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "ae_latent_space_pca_tsne.png"))
plt.close(fig)

print("Autoencoder diagnostics saved (not displayed inline). Proceeding to classifiers with the "
      f"{BEST_LATENT_DIM}-D latent representation.")

# %% [markdown]
# ## 8. ML Classifiers + RandomizedSearchCV Hyperparameter Distributions

# %%
N_ITER_SEARCH = 20      # random configurations sampled per classifier
INNER_CV      = 3       # inner CV folds used *inside* each RandomizedSearchCV

def get_param_distributions():
    return {
        "Decision Tree": (
            DecisionTreeClassifier(random_state=SEED),
            {
                "criterion": ["gini", "entropy"],
                "max_depth": [None, 3, 5, 8, 12, 16, 20],
                "min_samples_split": randint(2, 20),
                "min_samples_leaf": randint(1, 10),
            },
        ),
        "Random Forest": (
            RandomForestClassifier(random_state=SEED, n_jobs=-1),
            {
                "n_estimators": randint(100, 600),
                "max_depth": [None, 5, 10, 15, 20, 30],
                "min_samples_split": randint(2, 15),
                "min_samples_leaf": randint(1, 8),
                "max_features": ["sqrt", "log2", None],
            },
        ),
        "Gradient Boosting": (
            GradientBoostingClassifier(random_state=SEED),
            {
                "n_estimators": randint(80, 400),
                "learning_rate": loguniform(1e-3, 3e-1),
                "max_depth": randint(2, 6),
                "subsample": uniform(0.6, 0.4),
                "min_samples_split": randint(2, 15),
            },
        ),
        "AdaBoost": (
            AdaBoostClassifier(random_state=SEED),
            {
                "n_estimators": randint(50, 400),
                "learning_rate": loguniform(1e-3, 2.0),
            },
        ),
        "SVM": (
            SVC(probability=True, random_state=SEED),
            {
                "C": loguniform(1e-2, 1e3),
                "gamma": loguniform(1e-4, 1e1),
                "kernel": ["rbf", "poly", "sigmoid"],
            },
        ),
        "XGBoost": (
            XGBClassifier(eval_metric="logloss", random_state=SEED, n_jobs=-1, verbosity=0),
            {
                "n_estimators": randint(80, 500),
                "max_depth": randint(2, 10),
                "learning_rate": loguniform(1e-3, 3e-1),
                "subsample": uniform(0.6, 0.4),
                "colsample_bytree": uniform(0.6, 0.4),
            },
        ),
    }

def make_search(clf_name, n_iter=N_ITER_SEARCH, cv=INNER_CV):
    est, param_dist = get_param_distributions()[clf_name]
    return RandomizedSearchCV(
        estimator=est,
        param_distributions=param_dist,
        n_iter=n_iter,
        cv=cv,
        scoring="accuracy",
        random_state=SEED,
        n_jobs=-1,
        refit=True,
        error_score=0.0,
    )

def get_classifiers():
    return {name: None for name in get_param_distributions().keys()}

# %% [markdown]
# ## 9. Stratified 5-Fold Cross-Validation — **Training set ONLY** (addresses reviewer comment)
#
# **Reviewer comment addressed:** *"The manuscript lacks comprehensive cross-validation
# results. To properly evaluate the model's stability and performance, the authors
# should provide fold-wise results along with the standard deviation."*
#
# Each fold runs its own nested `RandomizedSearchCV` (outer 5-fold split, inner
# `INNER_CV`-fold random search). This version:
# - Stores **every individual fold's** Accuracy / Precision / Recall / F1 / AUCROC / Log Loss.
# - Returns the **mean AND standard deviation** across the 5 folds for every metric.
# - Runs a Shapiro-Wilk normality test on the fold accuracy distribution.
# Downstream, the raw per-fold values are collected into a long-format
# `cv_foldwise_df` table (Section 12) and visualized in Section 12.1.

# %%
def cross_validate_model(clf_name, X, y, n_splits=5):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=SEED)

    fold_metrics = {
        "Accuracy": [], "Precision": [], "Recall": [], "F1": [], "AUCROC": [], "Log Loss": []
    }

    for fold_idx, (tr_idx, te_idx) in enumerate(skf.split(X, y), start=1):
        Xtr, Xte = X[tr_idx], X[te_idx]
        ytr, yte = y[tr_idx], y[te_idx]

        scaler = StandardScaler().fit(Xtr)
        Xtr_s, Xte_s = scaler.transform(Xtr), scaler.transform(Xte)

        search = make_search(clf_name)
        search.fit(Xtr_s, ytr)
        clf = search.best_estimator_

        pred = clf.predict(Xte_s)
        proba = clf.predict_proba(Xte_s)

        fold_metrics["Accuracy"].append(accuracy_score(yte, pred))
        fold_metrics["Precision"].append(precision_score(yte, pred, average=AVERAGE, zero_division=0))
        fold_metrics["Recall"].append(recall_score(yte, pred, average=AVERAGE, zero_division=0))
        fold_metrics["F1"].append(f1_score(yte, pred, average=AVERAGE, zero_division=0))
        try:
            if N_CLASSES == 2:
                fold_metrics["AUCROC"].append(roc_auc_score(yte, proba[:, 1]))
            else:
                fold_metrics["AUCROC"].append(roc_auc_score(yte, proba, multi_class='ovr', average='macro'))
        except Exception:
            fold_metrics["AUCROC"].append(np.nan)
        fold_metrics["Log Loss"].append(log_loss(yte, proba, labels=list(range(N_CLASSES))))

    def sw_test(arr):
        arr = np.array(arr)
        if len(arr) < 3 or np.all(arr == arr[0]):
            return np.nan, np.nan
        stat, p = shapiro(arr)
        return stat, p

    sw_stat, sw_p = sw_test(fold_metrics["Accuracy"])
    normality = "Normal" if (not np.isnan(sw_p) and sw_p > 0.05) else "Not Normal"

    summary = {
        "CV Acc": np.mean(fold_metrics["Accuracy"]),       "CV Acc Std": np.std(fold_metrics["Accuracy"], ddof=1),
        "CV Precision": np.mean(fold_metrics["Precision"]), "CV Precision Std": np.std(fold_metrics["Precision"], ddof=1),
        "CV Recall": np.mean(fold_metrics["Recall"]),       "CV Recall Std": np.std(fold_metrics["Recall"], ddof=1),
        "CV F1": np.mean(fold_metrics["F1"]),               "CV F1 Std": np.std(fold_metrics["F1"], ddof=1),
        "AUCROC": np.nanmean(fold_metrics["AUCROC"]),       "AUCROC Std": np.nanstd(fold_metrics["AUCROC"], ddof=1),
        "Log Loss": np.mean(fold_metrics["Log Loss"]),      "Log Loss Std": np.std(fold_metrics["Log Loss"], ddof=1),
        "SW Stat": sw_stat, "SW p": sw_p, "Normality": normality,
        "fold_metrics": fold_metrics,   # raw per-fold values, consumed by Section 11/12
    }
    return summary

# %% [markdown]
# ## 10. Fit on Full Training Set → Evaluate on Validation / Test

# %%
def get_model_size_kb(clf):
    try:
        return len(pickle.dumps(clf)) / 1024.0
    except Exception:
        return np.nan

def train_and_evaluate(clf_name, X_train, y_train, X_eval, y_eval):
    scaler = StandardScaler().fit(X_train)
    Xtr_s = scaler.transform(X_train)
    Xev_s = scaler.transform(X_eval)

    search = make_search(clf_name)

    tracemalloc.start()
    t0 = time.perf_counter()
    search.fit(Xtr_s, y_train)
    train_time_s = time.perf_counter() - t0
    _, peak_bytes = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    peak_mem_mb = peak_bytes / (1024.0 ** 2)

    clf = search.best_estimator_
    best_params = search.best_params_

    train_pred = clf.predict(Xtr_s)
    train_acc = accuracy_score(y_train, train_pred)

    t0 = time.perf_counter()
    pred = clf.predict(Xev_s)
    proba = clf.predict_proba(Xev_s)
    t1 = time.perf_counter()
    inference_ms_per_image = ((t1 - t0) / max(len(X_eval), 1)) * 1000

    try:
        if N_CLASSES == 2:
            roc = roc_auc_score(y_eval, proba[:, 1])
        else:
            roc = roc_auc_score(y_eval, proba, multi_class='ovr', average='macro')
    except Exception:
        roc = np.nan

    metrics = {
        "Accuracy": accuracy_score(y_eval, pred),
        "Precision": precision_score(y_eval, pred, average=AVERAGE, zero_division=0),
        "Recall": recall_score(y_eval, pred, average=AVERAGE, zero_division=0),
        "F1-Score": f1_score(y_eval, pred, average=AVERAGE, zero_division=0),
        "ROC-AUC": roc,
        "Train Accuracy": train_acc,
        "Overfit Gap (Train-Eval)": train_acc - accuracy_score(y_eval, pred),
        "Training Time (s)": train_time_s,
        "Peak Train Memory (MB)": peak_mem_mb,
        "Model Size (KB)": get_model_size_kb(clf),
        "Inference Time (ms/Image)": inference_ms_per_image,
        "Best Params": best_params,
    }
    return clf, scaler, metrics, pred, proba

# %% [markdown]
# ## 11. Ablation Study — Handcrafted Only / ResNet50v2 Only / Fused / Fused+Autoencoder × 6 Classifiers
# Also builds the fold-wise long-format CV table used for the stability
# visualizations in Section 12.1.

# %%
feature_sets = {
    "Handcrafted Only":              (HC_train, HC_val, HC_test),
    "ResNet50v2 Only":                (RN_train, RN_val, RN_test),
    "Fused (HC + RN)":                (FUSED_train, FUSED_val, FUSED_test),
    "Fused + Autoencoder (Latent)":   (LATENT_train, LATENT_val, LATENT_test),
}

cv_rows, val_rows, test_rows = [], [], []
cv_foldwise_rows = []         # long format -> Ablation, Classifier, Fold, metric columns
cv_folds_store = {}           # (ablation, classifier) -> dict of fold-wise metric lists (kept for boxplots)
trained_models = {}           # (ablation, classifier) -> (clf, scaler)
predictions_store = {}        # (ablation, classifier) -> preds / probas on val & test

for ablation_name, (Xtr, Xva, Xte) in feature_sets.items():
    for clf_name in get_classifiers().keys():

        # (1) Stratified 5-Fold CV (nested with RandomizedSearchCV) — TRAIN ONLY
        cv_res = cross_validate_model(clf_name, Xtr, y_train, n_splits=5)
        fold_metrics = cv_res.pop("fold_metrics")
        cv_folds_store[(ablation_name, clf_name)] = fold_metrics
        cv_rows.append({"Ablation Study": ablation_name, "Classifier": clf_name, **cv_res})

        n_folds = len(fold_metrics["Accuracy"])
        for f in range(n_folds):
            cv_foldwise_rows.append({
                "Ablation Study": ablation_name,
                "Classifier": clf_name,
                "Fold": f + 1,
                "Accuracy": fold_metrics["Accuracy"][f],
                "Precision": fold_metrics["Precision"][f],
                "Recall": fold_metrics["Recall"][f],
                "F1": fold_metrics["F1"][f],
                "AUCROC": fold_metrics["AUCROC"][f],
                "Log Loss": fold_metrics["Log Loss"][f],
            })

        # (2) RandomizedSearchCV on full Train -> evaluate on Validation
        clf_v, scaler_v, val_metrics, val_pred, val_proba = train_and_evaluate(
            clf_name, Xtr, y_train, Xva, y_val)
        val_rows.append({"Ablation Study": ablation_name, "Classifier": clf_name,
                          **{k: v for k, v in val_metrics.items() if k != "Best Params"}})

        # (3) RandomizedSearchCV on full Train -> evaluate on Test
        clf_t, scaler_t, test_metrics, test_pred, test_proba = train_and_evaluate(
            clf_name, Xtr, y_train, Xte, y_test)
        test_rows.append({"Ablation Study": ablation_name, "Classifier": clf_name,
                           **{k: v for k, v in test_metrics.items() if k != "Best Params"}})

        trained_models[(ablation_name, clf_name)] = (clf_t, scaler_t)
        predictions_store[(ablation_name, clf_name)] = {
            "val_pred": val_pred, "val_proba": val_proba,
            "test_pred": test_pred, "test_proba": test_proba,
            "best_params": test_metrics["Best Params"],
        }

        print(f"[Done] {ablation_name:30s} | {clf_name:18s} | "
              f"CV Acc={cv_res['CV Acc']:.3f}±{cv_res['CV Acc Std']:.3f} | "
              f"Test Acc={test_metrics['Accuracy']:.3f} | "
              f"Train Time={test_metrics['Training Time (s)']:.2f}s | "
              f"Peak Mem={test_metrics['Peak Train Memory (MB)']:.1f}MB | "
              f"Model Size={test_metrics['Model Size (KB)']:.1f}KB | "
              f"BestParams={test_metrics['Best Params']}")

cv_df           = pd.DataFrame(cv_rows)
cv_foldwise_df  = pd.DataFrame(cv_foldwise_rows)   # fold-wise long-format table
val_df          = pd.DataFrame(val_rows)
test_df         = pd.DataFrame(test_rows)

# %% [markdown]
# ## 12. Results Tables (fold-wise CV export + mean±std columns)

# %%
cv_df.round(4).to_csv(os.path.join(OUT_DIR, "cv_results_train_summary.csv"), index=False)
cv_foldwise_df.round(4).to_csv(os.path.join(OUT_DIR, "cv_results_train_foldwise.csv"), index=False)
val_df.round(4).to_csv(os.path.join(OUT_DIR, "validation_results.csv"), index=False)
test_df.round(4).to_csv(os.path.join(OUT_DIR, "test_results.csv"), index=False)

best_params_rows = [
    {"Ablation Study": k[0], "Classifier": k[1], "Best Params": v["best_params"]}
    for k, v in predictions_store.items()
]
best_params_df = pd.DataFrame(best_params_rows)
best_params_df.to_csv(os.path.join(OUT_DIR, "best_hyperparameters.csv"), index=False)

# "mean (± std)" formatted display table — convenient for pasting straight into the manuscript
def fmt_mean_std(mean_col, std_col, decimals=4):
    return cv_df.apply(lambda r: f"{r[mean_col]:.{decimals}f} ± {r[std_col]:.{decimals}f}", axis=1)

cv_display_df = cv_df[["Ablation Study", "Classifier"]].copy()
for metric in ["CV Acc", "CV Precision", "CV Recall", "CV F1", "AUCROC", "Log Loss"]:
    cv_display_df[metric + " (mean ± SD)"] = fmt_mean_std(metric, metric + " Std")
cv_display_df.to_csv(os.path.join(OUT_DIR, "cv_results_train_mean_std_display.csv"), index=False)

with pd.ExcelWriter(os.path.join(OUT_DIR, "ablation_study_results.xlsx")) as writer:
    cv_df.round(4).to_excel(writer, sheet_name="CV_Train_Summary", index=False)
    cv_foldwise_df.round(4).to_excel(writer, sheet_name="CV_Train_Foldwise", index=False)
    cv_display_df.to_excel(writer, sheet_name="CV_Mean_Std_Display", index=False)
    val_df.round(4).to_excel(writer, sheet_name="Validation", index=False)
    test_df.round(4).to_excel(writer, sheet_name="Test", index=False)
    best_params_df.to_excel(writer, sheet_name="Best_Hyperparameters", index=False)

print("=== Cross-Validation SUMMARY (mean ± SD across 5 folds, nested RandomizedSearchCV) ===")
display(cv_display_df)

print("\n=== Cross-Validation FOLD-WISE Results (Training set) — all 120 rows "
      "(4 ablations × 6 classifiers × 5 folds) ===")
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(cv_foldwise_df.round(4))

print("\n=== Validation Set Results ===")
display(val_df.round(4))

print("\n=== Test Set Results ===")
display(test_df.round(4))

print("\n=== Selected Hyperparameters (Test-fit models) ===")
display(best_params_df)

# %% [markdown]
# ## 12.1 Fold-Wise Cross-Validation Visualization (Reviewer-Requested)
# Directly addresses the reviewer comment: shows **every individual fold's** result
# (not just an aggregate), **mean ± standard deviation** error bars, and a
# **standard-deviation heatmap** summarizing model stability across all
# ablation × classifier combinations. As with every other figure in this
# notebook, these are saved as PNGs to `OUT_DIR` but are not rendered inline
# on the output screen (see the global note at the top of the notebook).

# %%
clf_names = list(get_classifiers().keys())
ablation_order = list(feature_sets.keys())

# ── 12.1a Per-fold Accuracy trajectories (line plot), one panel per ablation ──
fig, axes = plt.subplots(1, len(ablation_order), figsize=(24, 5), sharey=True)
for ax, ablation_name in zip(axes, ablation_order):
    sub = cv_foldwise_df[cv_foldwise_df["Ablation Study"] == ablation_name]
    for clf_name in clf_names:
        s = sub[sub["Classifier"] == clf_name].sort_values("Fold")
        ax.plot(s["Fold"], s["Accuracy"], marker="o", linewidth=1.8, markersize=5,
                color=PALETTE_CLASSIFIER[clf_name], label=clf_name)
    ax.set_title(ablation_name, fontsize=10, color=PALETTE_ABLATION.get(ablation_name, "#212529"))
    ax.set_xlabel("Fold"); ax.set_xticks(range(1, 6))
axes[0].set_ylabel("Fold Accuracy")
handles, labels = axes[-1].get_legend_handles_labels()
fig.legend(handles, labels, loc="upper center", ncol=6, bbox_to_anchor=(0.5, 1.08), frameon=False)
plt.suptitle("Fold-Wise CV Accuracy Across All 5 Folds (Training Set, Tuned Models)",
             fontweight="bold", y=1.14)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_foldwise_accuracy_lines.png"), bbox_inches="tight")
plt.close('all')

# ── 12.1b Mean ± SD error-bar plot per classifier x ablation (CV Accuracy) ────
fig, ax = plt.subplots(figsize=(13, 6))
x = np.arange(len(clf_names))
width = 0.19
for i, ablation_name in enumerate(ablation_order):
    sub = cv_df[cv_df["Ablation Study"] == ablation_name].set_index("Classifier").loc[clf_names]
    ax.errorbar(x + (i - 1.5) * width, sub["CV Acc"], yerr=sub["CV Acc Std"],
                fmt="o", capsize=4, markersize=7, linewidth=1.6,
                color=PALETTE_ABLATION[ablation_name], label=ablation_name)
ax.set_xticks(x); ax.set_xticklabels(clf_names, rotation=25, ha="right")
ax.set_ylabel("CV Accuracy (mean ± SD, 5 folds)")
ax.set_title("Cross-Validation Stability: Mean ± Standard Deviation of Fold Accuracy")
style_ablation_legend(ax)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_mean_std_errorbars.png"))
plt.close('all')

# ── 12.1c Boxplots of fold-wise Accuracy, annotated with mean ± SD ────────────
fig, axes = plt.subplots(1, len(ablation_order), figsize=(22, 5), sharey=True)
box_colors = ordered_classifier_colors(clf_names)
for ax, ablation_name in zip(axes, feature_sets.keys()):
    data = [cv_folds_store[(ablation_name, c)]["Accuracy"] for c in clf_names]
    bp = ax.boxplot(data, labels=clf_names, patch_artist=True,
                     medianprops=dict(color="#212529", linewidth=1.6))
    for patch, color in zip(bp['boxes'], box_colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.75)
        patch.set_edgecolor("#212529")
    # annotate each box with mean ± SD text
    summary_sub = cv_df[cv_df["Ablation Study"] == ablation_name].set_index("Classifier").loc[clf_names]
    ymax = ax.get_ylim()[1]
    for j, c in enumerate(clf_names, start=1):
        m, s = summary_sub.loc[c, "CV Acc"], summary_sub.loc[c, "CV Acc Std"]
        ax.text(j, ymax, f"{m:.3f}±{s:.3f}", ha="center", va="bottom", fontsize=7, rotation=90)
    ax.set_title(ablation_name, fontsize=10, color=PALETTE_ABLATION.get(ablation_name, "#212529"))
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylim(top=ax.get_ylim()[1] * 1.18)
axes[0].set_ylabel("CV Fold Accuracy")
plt.suptitle("5-Fold CV Accuracy Distribution — annotated with Mean ± SD (Training Set, Tuned Models)",
             fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_accuracy_boxplots_annotated.png"))
plt.close('all')

# ── 12.1d Standard-deviation heatmap across all metrics (stability overview) ──
std_cols = ["CV Acc Std", "CV Precision Std", "CV Recall Std", "CV F1 Std", "AUCROC Std"]
fig, axes = plt.subplots(1, len(ablation_order), figsize=(24, 5.5), sharey=True)
for ax, ablation_name in zip(axes, ablation_order):
    sub = cv_df[cv_df["Ablation Study"] == ablation_name].set_index("Classifier")[std_cols].loc[clf_names]
    sns.heatmap(sub, annot=True, fmt=".3f", cmap="OrRd", ax=ax, cbar=(ablation_name == ablation_order[-1]),
                linewidths=0.5, linecolor="white", annot_kws={"fontsize": 8})
    ax.set_title(ablation_name, fontsize=10, color=PALETTE_ABLATION.get(ablation_name, "#212529"))
    ax.set_ylabel("")
axes[0].set_ylabel("Classifier")
plt.suptitle("Cross-Validation Standard-Deviation Heatmap (Lower = More Stable)", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_std_heatmap.png"), bbox_inches="tight")
plt.close('all')

# ── 12.1e CV Accuracy with SD band, focused on the proposed pipeline ──────────
proposed_cv = cv_df[cv_df["Ablation Study"] == "Fused + Autoencoder (Latent)"].set_index("Classifier").loc[clf_names]
fig, ax = plt.subplots(figsize=(9, 5.5))
bars = ax.bar(clf_names, proposed_cv["CV Acc"], yerr=proposed_cv["CV Acc Std"], capsize=5,
              color=[PALETTE_CLASSIFIER[c] for c in clf_names], edgecolor="#212529", linewidth=0.8)
for i, c in enumerate(clf_names):
    m, s = proposed_cv.loc[c, "CV Acc"], proposed_cv.loc[c, "CV Acc Std"]
    ax.text(i, m + s + 0.01, f"{m:.3f}±{s:.3f}", ha="center", va="bottom", fontsize=8, fontweight="bold")
ax.set_ylabel("CV Accuracy (mean ± SD)")
ax.set_title("Proposed Pipeline (Fused + Autoencoder Latent) — CV Stability per Classifier")
ax.tick_params(axis='x', rotation=25)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_proposed_pipeline_mean_std.png"))
plt.close('all')

# %% [markdown]
# ## 13. Visualization — Accuracy & F1 Comparison (Test Set)

# %%
plt.figure(figsize=(12, 6))
pivot_acc = test_df.pivot(index="Classifier", columns="Ablation Study", values="Accuracy")[ablation_order]
ax = pivot_acc.plot(kind="bar", ax=plt.gca(),
                     color=[PALETTE_ABLATION[c] for c in pivot_acc.columns],
                     edgecolor="white", linewidth=0.6)
annotate_bars(ax, fmt="{:.2f}", fontsize=7.5)
plt.title("Test Accuracy by Classifier and Feature Set")
plt.ylabel("Accuracy"); plt.xticks(rotation=30, ha='right')
style_ablation_legend(ax)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "test_accuracy_comparison.png"))
plt.close('all')

# %%
plt.figure(figsize=(8.5, 6.5))
pivot_f1 = test_df.pivot(index="Classifier", columns="Ablation Study", values="F1-Score")[ablation_order]
sns.heatmap(pivot_f1, annot=True, fmt=".3f", cmap="crest", cbar_kws={"label": "F1-Score"},
            linewidths=0.5, linecolor="white", annot_kws={"fontsize": 9, "fontweight": "bold"})
plt.title("Test F1-Score Heatmap")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "f1_heatmap.png"))
plt.close('all')

# %% [markdown]
# ## 14. Visualization — CV Accuracy Distribution (Boxplots, Training set)
# (kept for continuity with the original manuscript figure numbering; the
# annotated version with mean±SD is in Section 12.1c)

# %%
fig, axes = plt.subplots(1, len(feature_sets), figsize=(22, 5), sharey=True)
box_colors = ordered_classifier_colors(clf_names)
for ax, ablation_name in zip(axes, feature_sets.keys()):
    data = [cv_folds_store[(ablation_name, c)]["Accuracy"] for c in clf_names]
    bp = ax.boxplot(data, labels=clf_names, patch_artist=True, medianprops=dict(color="#212529", linewidth=1.6))
    for patch, color in zip(bp['boxes'], box_colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.75)
        patch.set_edgecolor("#212529")
    ax.set_title(ablation_name, fontsize=10, color=PALETTE_ABLATION.get(ablation_name, "#212529"))
    ax.tick_params(axis='x', rotation=45)
axes[0].set_ylabel("CV Fold Accuracy")
plt.suptitle("5-Fold Cross-Validation Accuracy Distribution (Training Set Only, Tuned Models)", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_accuracy_boxplots.png"))
plt.close('all')

# %% [markdown]
# ## 15. Visualization — ROC Curves & Confusion Matrices (best model per feature set, Test set)

# %%
best_per_ablation = test_df.loc[test_df.groupby("Ablation Study")["Accuracy"].idxmax()]

plt.figure(figsize=(7.5, 6.5))
for _, row in best_per_ablation.iterrows():
    key = (row["Ablation Study"], row["Classifier"])
    proba = predictions_store[key]["test_proba"]
    color = PALETTE_ABLATION.get(row["Ablation Study"], "#868E96")
    lw = 3.0 if row["Ablation Study"] == "Fused + Autoencoder (Latent)" else 1.8
    if N_CLASSES == 2:
        fpr, tpr, _ = roc_curve(y_test, proba[:, 1])
        roc_auc_val = auc(fpr, tpr)
        plt.plot(fpr, tpr, label=f"{row['Ablation Study']} - {row['Classifier']} (AUC={roc_auc_val:.3f})",
                 color=color, linewidth=lw)
plt.plot([0, 1], [0, 1], 'k--', alpha=0.4, linewidth=1)
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("ROC Curves — Best Classifier per Feature Set (Test Set)")
plt.legend(fontsize=8)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "roc_curves_test.png"))
plt.close('all')

# %%
n = len(best_per_ablation)
fig, axes = plt.subplots(1, n, figsize=(5 * n, 4))
if n == 1:
    axes = [axes]
for ax, (_, row) in zip(axes, best_per_ablation.iterrows()):
    key = (row["Ablation Study"], row["Classifier"])
    pred = predictions_store[key]["test_pred"]
    cm = confusion_matrix(y_test, pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_, yticklabels=le.classes_, ax=ax,
                linewidths=0.5, linecolor="white", cbar=False,
                annot_kws={"fontsize": 10, "fontweight": "bold"})
    ax.set_title(f"{row['Ablation Study']}\n{row['Classifier']}", fontsize=9,
                 color=PALETTE_ABLATION.get(row["Ablation Study"], "#212529"))
    ax.set_xlabel("Predicted"); ax.set_ylabel("Actual")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "confusion_matrices_test.png"))
plt.close('all')

# %% [markdown]
# ## 16. Visualization — Normality Check (Shapiro-Wilk on CV folds) & Inference Time

# %%
plt.figure(figsize=(12, 5))
ax = sns.barplot(data=cv_df, x="Classifier", y="SW p", hue="Ablation Study",
                  hue_order=ablation_order, palette=PALETTE_ABLATION, edgecolor="white")
plt.axhline(0.05, color=ACCENT_BAD, linestyle='--', linewidth=1.6, label='alpha = 0.05')
plt.title("Shapiro-Wilk Normality Test (p-value) on 5-Fold CV Accuracy")
plt.ylabel("SW p-value"); plt.xticks(rotation=30, ha='right')
style_ablation_legend(ax)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "shapiro_wilk_pvalues.png"))
plt.close('all')

# %%
plt.figure(figsize=(12, 6))
pivot_inf = test_df.pivot(index="Classifier", columns="Ablation Study", values="Inference Time (ms/Image)")[ablation_order]
ax = pivot_inf.plot(kind="bar", ax=plt.gca(),
                     color=[PALETTE_ABLATION[c] for c in pivot_inf.columns],
                     edgecolor="white", linewidth=0.6)
annotate_bars(ax, fmt="{:.2f}", fontsize=7.5)
plt.title("Inference Time by Classifier and Feature Set (Test Set)")
plt.ylabel("ms / image"); plt.xticks(rotation=30, ha='right')
style_ablation_legend(ax)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "inference_time_comparison.png"))
plt.close('all')

# %% [markdown]
# ## 17. Proposed Pipeline (Fused + Autoencoder Latent) — CV Metric Comparison

# %%
metrics_to_plot = ["CV Acc", "CV Precision", "CV Recall", "CV F1", "AUCROC"]
fused_cv = cv_df[cv_df["Ablation Study"] == "Fused + Autoencoder (Latent)"].set_index("Classifier")[metrics_to_plot]
metric_colors = ["#12B886", "#4C6EF5", "#F59F00", "#E64980", "#9C36B5"]
ax = fused_cv.plot(kind="bar", figsize=(10, 6), color=metric_colors, edgecolor="white", linewidth=0.6)
annotate_bars(ax, fmt="{:.2f}", fontsize=7.5)
plt.title("CV Metrics — Proposed Pipeline (Fused + Autoencoder Latent Features, Tuned Models)")
plt.ylabel("Score"); plt.xticks(rotation=30, ha='right')
plt.legend(title="Metric", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "cv_metrics_proposed_pipeline.png"))
plt.close('all')

# %% [markdown]
# ## 18. Overfitting Analysis
# Compares **Train Accuracy** against **CV Accuracy**, **Validation Accuracy**, and
# **Test Accuracy**. The proposed `Fused + Autoencoder (Latent)` pipeline is expected
# to show the smallest gap because the regularized autoencoder compresses ~2000+
# fused dimensions down to a compact latent space, acting as a strong regularizer
# against high-dimensional overfitting.

# %%
overfit_df = pd.DataFrame({
    "Ablation Study": test_df["Ablation Study"].values,
    "Classifier": test_df["Classifier"].values,
    "Train Accuracy": test_df["Train Accuracy"].values,
    "CV Accuracy": cv_df["CV Acc"].values,
    "CV Accuracy Std": cv_df["CV Acc Std"].values,
    "Validation Accuracy": val_df["Accuracy"].values,
    "Test Accuracy": test_df["Accuracy"].values,
})
overfit_df["Overfit Gap (Train-Test)"] = overfit_df["Train Accuracy"] - overfit_df["Test Accuracy"]
overfit_df.round(4).to_csv(os.path.join(OUT_DIR, "overfit_analysis.csv"), index=False)

# --- 18a. Train vs CV vs Val vs Test accuracy, per classifier, for EVERY ablation ---
fig, axes = plt.subplots(1, len(ablation_order), figsize=(24, 5.5), sharey=True)
stage_cols = ["Train Accuracy", "CV Accuracy", "Validation Accuracy", "Test Accuracy"]
stage_colors = ["#495057", "#4C6EF5", "#F59F00", "#12B886"]
for ax, ablation_name in zip(axes, ablation_order):
    sub = overfit_df[overfit_df["Ablation Study"] == ablation_name].set_index("Classifier")[stage_cols]
    sub.plot(kind="bar", ax=ax, color=stage_colors, edgecolor="white", linewidth=0.5, legend=False)
    ax.set_title(ablation_name, fontsize=10, color=PALETTE_ABLATION.get(ablation_name, "#212529"))
    ax.tick_params(axis='x', rotation=45)
    ax.set_xlabel("")
axes[0].set_ylabel("Accuracy")
handles, labels = axes[-1].get_legend_handles_labels()
fig.legend(handles, stage_cols, loc="upper center", ncol=4, bbox_to_anchor=(0.5, 1.06), frameon=False)
plt.suptitle("Overfitting Check: Train vs CV vs Validation vs Test Accuracy", fontweight="bold", y=1.1)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "overfit_train_vs_eval_accuracy.png"), bbox_inches="tight")
plt.close('all')

# --- 18b. Generalization-gap heatmap (Train - Test) across every ablation x classifier ---
plt.figure(figsize=(8.5, 6.5))
gap_pivot = overfit_df.pivot(index="Classifier", columns="Ablation Study", values="Overfit Gap (Train-Test)")[ablation_order]
sns.heatmap(gap_pivot, annot=True, fmt=".3f", cmap="RdYlGn_r", center=0,
            cbar_kws={"label": "Train − Test Accuracy Gap"}, linewidths=0.5, linecolor="white",
            annot_kws={"fontsize": 9, "fontweight": "bold"})
plt.title("Generalization Gap (Higher = More Overfit)")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "overfit_gap_heatmap.png"))
plt.close('all')

# --- 18c. Focused view: proposed pipeline only, sorted by gap ---
proposed_gap = overfit_df[overfit_df["Ablation Study"] == "Fused + Autoencoder (Latent)"] \
    .sort_values("Overfit Gap (Train-Test)")
plt.figure(figsize=(9, 5.5))
bar_colors = [ACCENT_GOOD if g < 0.05 else ACCENT_BAD for g in proposed_gap["Overfit Gap (Train-Test)"]]
ax = plt.barh(proposed_gap["Classifier"], proposed_gap["Overfit Gap (Train-Test)"], color=bar_colors, edgecolor="white")
plt.axvline(0.05, color="#495057", linestyle="--", linewidth=1.3, label="5% gap threshold")
plt.xlabel("Train − Test Accuracy Gap"); plt.title("Overfitting Gap — Proposed Pipeline (Fused + Autoencoder)")
for i, g in enumerate(proposed_gap["Overfit Gap (Train-Test)"]):
    plt.text(g, i, f" {g:.3f}", va="center", fontsize=9, fontweight="bold",
              color="#212529", ha="left" if g >= 0 else "right")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "overfit_gap_proposed_pipeline.png"))
plt.close('all')

# %% [markdown]
# ## 19. Prediction Confidence Distribution — Final Chosen Model

# %%
best_overall_row = test_df.loc[test_df["Accuracy"].idxmax()]
BEST_ABLATION = best_overall_row["Ablation Study"]
BEST_CLASSIFIER = best_overall_row["Classifier"]
best_key = (BEST_ABLATION, BEST_CLASSIFIER)

best_test_pred = predictions_store[best_key]["test_pred"]
best_test_proba = predictions_store[best_key]["test_proba"]
confidence = best_test_proba.max(axis=1)
is_correct = (best_test_pred == y_test)

conf_df = pd.DataFrame({
    "Confidence": confidence,
    "Correct": np.where(is_correct, "Correct", "Incorrect"),
    "True Class": le.inverse_transform(y_test),
    "Predicted Class": le.inverse_transform(best_test_pred),
})
conf_df.round(4).to_csv(os.path.join(OUT_DIR, "confidence_distribution_best_model.csv"), index=False)

# --- 19a. Overlaid histogram: correct vs incorrect ---
plt.figure(figsize=(9, 5.5))
safe_histplot(data=conf_df, x="Confidence", hue="Correct", bins=25, kde=True,
              palette={"Correct": ACCENT_GOOD, "Incorrect": ACCENT_BAD},
              element="step", stat="density", common_norm=False, alpha=0.6, linewidth=1.4)
plt.title(f"Prediction Confidence Distribution — {BEST_ABLATION} + {BEST_CLASSIFIER}\n(Final Selected Model, Test Set)")
plt.xlabel("Predicted Confidence (max class probability)"); plt.ylabel("Density")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "confidence_distribution_best_model.png"))
plt.close('all')

# --- 19b. Confidence spread per true class (violin, falls back to box if degenerate) ---
plt.figure(figsize=(9, 5.5))
safe_violinplot(data=conf_df, x="True Class", y="Confidence", hue="Correct",
                 split=True, palette={"Correct": ACCENT_GOOD, "Incorrect": ACCENT_BAD},
                 inner="quartile", cut=0)
plt.title(f"Per-Class Confidence — {BEST_ABLATION} + {BEST_CLASSIFIER}")
plt.ylim(0, 1.05)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "confidence_distribution_per_class.png"))
plt.close('all')

# --- 19c. Confidence comparison across ALL classifiers within the winning ablation ---
rows = []
for clf_name in clf_names:
    k = (BEST_ABLATION, clf_name)
    proba = predictions_store[k]["test_proba"]
    pred = predictions_store[k]["test_pred"]
    conf = proba.max(axis=1)
    correct = (pred == y_test)
    for c, ok in zip(conf, correct):
        rows.append({"Classifier": clf_name, "Confidence": c, "Correct": "Correct" if ok else "Incorrect"})
clf_conf_df = pd.DataFrame(rows)

plt.figure(figsize=(11, 6))
ax = sns.boxplot(data=clf_conf_df, x="Classifier", y="Confidence", hue="Correct",
                  palette={"Correct": ACCENT_GOOD, "Incorrect": ACCENT_BAD})
plt.title(f"Confidence Spread by Classifier — {BEST_ABLATION} Feature Set")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "confidence_distribution_all_classifiers.png"))
plt.close('all')

# %% [markdown]
# ## 20. Resource-Utilization Analysis — Why the Final Model Wins on Efficiency Too

# %%
resource_cols = ["Training Time (s)", "Peak Train Memory (MB)", "Model Size (KB)", "Inference Time (ms/Image)"]
resource_df = test_df[["Ablation Study", "Classifier", "Accuracy"] + resource_cols].copy()
resource_df.round(4).to_csv(os.path.join(OUT_DIR, "resource_utilization.csv"), index=False)

# --- 20a. Small multiples: each resource metric by classifier x ablation ---
fig, axes = plt.subplots(2, 2, figsize=(16, 11))
for ax, metric in zip(axes.flatten(), resource_cols):
    pivot = resource_df.pivot(index="Classifier", columns="Ablation Study", values=metric)[ablation_order]
    pivot.plot(kind="bar", ax=ax, color=[PALETTE_ABLATION[c] for c in pivot.columns],
               edgecolor="white", linewidth=0.5, legend=False)
    ax.set_title(metric, fontsize=11)
    ax.tick_params(axis='x', rotation=30)
    ax.set_xlabel("")
handles, labels = axes[0, 0].get_legend_handles_labels()
fig.legend(handles, ablation_order, loc="upper center", ncol=4, bbox_to_anchor=(0.5, 1.03), frameon=False)
plt.suptitle("Resource Utilization Across Feature Sets and Classifiers", fontweight="bold", y=1.05)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "resource_utilization_grid.png"), bbox_inches="tight")
plt.close('all')

# --- 20b. Efficiency frontier: Accuracy vs Inference Time, bubble size = Model Size ---
plt.figure(figsize=(9.5, 7))
for ablation_name in ablation_order:
    sub = resource_df[resource_df["Ablation Study"] == ablation_name]
    is_proposed = ablation_name == "Fused + Autoencoder (Latent)"
    plt.scatter(sub["Inference Time (ms/Image)"], sub["Accuracy"],
                s=(sub["Model Size (KB)"].clip(lower=1) ** 0.6) * 8,
                color=PALETTE_ABLATION[ablation_name],
                edgecolor="#212529", linewidth=1.1 if is_proposed else 0.4,
                alpha=0.85, label=ablation_name, zorder=3 if is_proposed else 2)
best_pt = resource_df[(resource_df["Ablation Study"] == BEST_ABLATION) & (resource_df["Classifier"] == BEST_CLASSIFIER)]
plt.scatter(best_pt["Inference Time (ms/Image)"], best_pt["Accuracy"], s=260, facecolors='none',
            edgecolors="#212529", linewidth=2.2, zorder=4)
plt.annotate(f"  Final model:\n  {BEST_ABLATION}\n  + {BEST_CLASSIFIER}",
             (best_pt["Inference Time (ms/Image)"].values[0], best_pt["Accuracy"].values[0]),
             fontsize=9, fontweight="bold", color="#212529")
plt.xlabel("Inference Time (ms / image)  →  lower is better")
plt.ylabel("Test Accuracy  →  higher is better")
plt.title("Efficiency Frontier: Accuracy vs. Inference Time\n(bubble size ∝ serialized model size)")
style_ablation_legend(plt.gca())
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "efficiency_frontier.png"))
plt.close('all')

# --- 20c. Average resource footprint per ablation (summary bars) ---
avg_resource = resource_df.groupby("Ablation Study")[resource_cols + ["Accuracy"]].mean().loc[ablation_order]
fig, axes = plt.subplots(1, 4, figsize=(20, 4.5))
for ax, metric in zip(axes, resource_cols):
    colors = [PALETTE_ABLATION[a] for a in avg_resource.index]
    bars = ax.bar(avg_resource.index, avg_resource[metric], color=colors, edgecolor="white")
    ax.set_title(metric, fontsize=10.5)
    ax.tick_params(axis='x', rotation=35)
    for b, v in zip(bars, avg_resource[metric]):
        ax.text(b.get_x() + b.get_width() / 2, v, f"{v:.2f}", ha="center", va="bottom", fontsize=8, fontweight="bold")
plt.suptitle("Average Resource Footprint by Feature Set (Across All 6 Classifiers)", fontweight="bold")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "resource_footprint_summary.png"), bbox_inches="tight")
plt.close('all')

# %% [markdown]
# ## 21. Proposed Model (Fused + Autoencoder) Justification

# %%
# Justification is scoped to the proposed pipeline specifically — i.e. the best
# classifier *within* the "Fused + Autoencoder (Latent)" ablation — rather than
# whichever ablation/classifier happened to score highest overall.
PROPOSED_ABLATION = "Fused + Autoencoder (Latent)"
proposed_test_df = test_df[test_df["Ablation Study"] == PROPOSED_ABLATION]
proposed_best_row = proposed_test_df.loc[proposed_test_df["Accuracy"].idxmax()]
PROPOSED_CLASSIFIER = proposed_best_row["Classifier"]
proposed_key = (PROPOSED_ABLATION, PROPOSED_CLASSIFIER)

print("Best hyperparameters found (proposed model):", predictions_store[proposed_key]["best_params"])

baseline_mask = resource_df["Ablation Study"].isin(["Fused (HC + RN)", "ResNet50v2 Only"])
baseline_avg = resource_df.loc[baseline_mask, resource_cols].mean()
chosen_row = resource_df[(resource_df["Ablation Study"] == PROPOSED_ABLATION) & (resource_df["Classifier"] == PROPOSED_CLASSIFIER)].iloc[0]
chosen_cv_row = cv_df[(cv_df["Ablation Study"] == PROPOSED_ABLATION) & (cv_df["Classifier"] == PROPOSED_CLASSIFIER)].iloc[0]

print("\n" + "=" * 70)
print("FUSION + AUTOENCODER JUSTIFICATION (PROPOSED MODEL)")
print("=" * 70)
print(f"Selected pipeline  : {PROPOSED_ABLATION}  +  {PROPOSED_CLASSIFIER}")
print(f"Selected latent dim: {BEST_LATENT_DIM}")
print(f"CV Accuracy (5-fold): {chosen_cv_row['CV Acc']:.4f} ± {chosen_cv_row['CV Acc Std']:.4f}  (mean ± SD)")
print(f"Test Accuracy      : {chosen_row['Accuracy']:.4f}")
print(f"Overfit Gap        : {overfit_df.loc[(overfit_df['Ablation Study']==PROPOSED_ABLATION) & (overfit_df['Classifier']==PROPOSED_CLASSIFIER), 'Overfit Gap (Train-Test)'].values[0]:.4f}  (lower = better generalization)")
print("-" * 70)
for col in resource_cols:
    delta_pct = (1 - chosen_row[col] / baseline_avg[col]) * 100 if baseline_avg[col] else np.nan
    direction = "lower" if delta_pct > 0 else "higher"
    print(f"{col:28s}: {chosen_row[col]:10.3f}   "
          f"({abs(delta_pct):.1f}% {direction} than avg of ResNet-only / raw-fused models)")
print("=" * 70)
print(
    "Justification: the regularized Fused + Autoencoder (Latent) pipeline compresses the "
    "raw handcrafted + ResNet50V2 feature vector into a compact latent code whose "
    f"dimensionality ({BEST_LATENT_DIM}) was itself chosen by a validation-loss search "
    "rather than fixed in advance. Combined with RandomizedSearchCV hyperparameter "
    "tuning for every downstream classifier, the model shows both high mean CV "
    "accuracy and a low standard deviation across folds, indicating stable, "
    "reproducible performance rather than a lucky split. This cuts training time, "
    "peak memory during fit, serialized model size, and per-image inference latency "
    "relative to feeding classifiers the full ResNet-only or raw-fused vectors "
    "directly — while matching or exceeding their test accuracy and showing a "
    "small train-test generalization gap. That combination of strong accuracy, fold-"
    "wise stability, controlled overfitting, and the lowest resource footprint "
    "is why the Fused + Autoencoder pipeline is proposed as the final production model."
)

print("\nAll result tables + figures saved to:", OUT_DIR)
